name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: 'Terraform Init'
        working-directory: ./test
        run: terraform init

      - name: 'Terraform Validate'
        working-directory: ./test
        run: terraform validate
