name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: 'Install Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: 'Run Go Test Cases'
        working-directory: ./test
        run: go run main.go > expected_output.json

      - name: 'Terraform Init'
        working-directory: ./test
        id: init
        run: terraform init

      - name: 'Terraform Validate'
        working-directory: ./test
        id: validate
        run: terraform validate

      - name: 'Terraform Plan'
        working-directory: ./test
        id: plan
        run: terraform plan

      - name: 'Terraform Apply'
        working-directory: ./test
        id: apply
        run: terraform apply -auto-approve

      - name: 'Get Terraform Outputs'
        working-directory: ./test
        run: terraform output -json | tail -n +1 > terraform_output.json

      - name: 'Compare Outputs'
        working-directory: ./test
        run: |
          echo "Expected Output:"
          cat expected_output.json
          echo "Terraform Output:"
          cat terraform_output.json

          # Extract values from JSON and convert to a comparable format
          expected=$(jq -c 'sort_by(.resource_name, .namespace, .vcluster_name)' expected_output.json)
          terraform=$(jq -c '.updated_names.value | sort_by(.resource_name, .namespace, .vcluster_name)' terraform_output.json)

          echo "Parsed Expected: $expected"
          echo "Parsed Terraform: $terraform"

          if [ "$expected" != "$terraform" ]; then
            echo "Output does not match expected value!"
            echo "Expected: $expected"
            echo "Terraform: $terraform"
            exit 1
          else
            echo "Output matches expected value."
          fi

      - name: 'Terraform Destroy'
        working-directory: ./test
        if: always()
        run: terraform destroy -auto-approve
